runs:
  using: 'composite'
  steps:      
    #Scan current commit with semgrep and generate JSON report  
    - name: Checkout
      uses: actions/checkout@v4
      

    - name: Run semgrep
      shell: bash
      id: semgrep_scan
      run: |
        docker run --rm -v .:/src -w /src \
        semgrep/semgrep \
        semgrep scan \
        --json \
        -o "semgrep-${{ github.event.repository.name }}-${{ github.head_ref || github.ref_name }}.json" \
        --config=p/xss \
        --config=p/jwt \
        --config=p/gitlab \
        --config=p/default \
        --config=p/comment \
        --config=p/shadow-ai \
        --config=p/cwe-top-25 \
        --config=p/trailofbits \
        --config=p/owasp-top-ten \
        --config=p/sql-injection \
        --config=p/security-audit \
        --config=p/secure-defaults \
        --config=p/command-injection \
        --config=p/insecure-transport \
        --config=p/r2c-security-audit \
        --config=p/insecure-transport-jsnode \
        --config=p/php \
        --config=p/php-laravel \
        --config=p/phpcs-security-audit \
        --config=p/java \
        --config=p/findsecbugs \
        --config=p/gosec \
        --config=p/golang \
        --config=p/semgrep-go-correctness \
        --config=p/python \
        --config=p/bandit \
        --config=p/react \
        --config=p/eslint \
        --config=p/nextjs \
        --config=p/nodejs \
        --config=p/expressjs \
        --config=p/javascript \
        --config=p/typescript \
        --config=p/react-team-tier \
        --config=p/headless-browser \
        --config=p/react-best-practice \
        .


    - name: Upload semgrep report to artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: semgrep-${{ github.event.repository.name }}-${{ github.head_ref || github.ref_name }}-json
        path: semgrep-${{ github.event.repository.name }}-${{ github.head_ref || github.ref_name }}.json
        #retention-days: 1