inputs:
  CHART_NAME:
    type: string
    required: true
  CHART_VER:
    type: string
    required: true
  CHART_VALUES:
    type: string
    required: true
  SERVICE_NAME:
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    # - name: Set env for Trivy (dev/test/prod)
    #   if: steps.tool_for_scanning.outputs.scan_tool == 'trivy'
    #   shell: bash
    #   run: |
    #     # Set env for Trivy (dev/test/prod)

    #     exit_code_env_trivy=0

    #     if [[ "$GITHUB_WORKFLOW" == *"prod"* ]]; then
    #       exit_code_env_trivy=1
    #       echo "Running Helm scan in prod"
    #       echo "If High or Critical vulnerabilities are found, the pipeline will fail"
    #     else
    #       echo "Running Helm scan in non-prod environment"
    #       echo "You can find reports in artifacts"
    #     fi

    #     echo "exit_code_env_trivy=$exit_code_env_trivy" >> $GITHUB_OUTPUT
    #   id: exit_code_env_trivy
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Helm fetch and template
      shell: bash
      run: |
        helm fetch oci://ghcr.io/jjoinvest/jjo-helm-charts/${{ inputs.CHART_NAME }} \
          --version ${{ inputs.CHART_VER }} --untar

        helm template ${{ inputs.SERVICE_NAME }} ./${{ inputs.CHART_NAME }} \
          --values=${{ inputs.CHART_VALUES }} > \
          ${{ inputs.SERVICE_NAME }}-${{ inputs.CHART_NAME }}-${{ inputs.CHART_VER }}.yaml
    - name: Run Trivy (JSON report)
      uses: aquasecurity/trivy-action@0.29.0
      with:
        scan-type: "config"
        hide-progress: true
        format: "json"
        scan-ref: "${{ inputs.SERVICE_NAME }}-${{ inputs.CHART_NAME }}-${{ inputs.CHART_VER }}.yaml"
        output: "${{ inputs.SERVICE_NAME }}-${{ inputs.CHART_NAME }}-${{ inputs.CHART_VER }}.json"
        exit-code: 0
    - name: Upload Trivy (JSON report)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.SERVICE_NAME }}-${{ inputs.CHART_NAME }}-${{ inputs.CHART_VER }}-json
        path: ${{ inputs.SERVICE_NAME }}-${{ inputs.CHART_NAME }}-${{ inputs.CHART_VER }}.json
        retention-days: 1
    - name: Run Trivy (HTML report)
      uses: aquasecurity/trivy-action@0.29.0
      with:
        scan-type: "config"
        hide-progress: true
        format: "template"
        scan-ref: "${{ inputs.SERVICE_NAME }}-${{ inputs.CHART_NAME }}-${{ inputs.CHART_VER }}.yaml"
        template: "@$HOME/.local/bin/trivy-bin/contrib/html.tpl"
        output: "${{ inputs.SERVICE_NAME }}-${{ inputs.CHART_NAME }}-${{ inputs.CHART_VER }}.html"
        # severity: 'CRITICAL,HIGH'
        # exit-code: ${{ steps.exit_code_env_trivy.outputs.exit_code_env_trivy }}
        skip-setup-trivy: true
    - name: Upload Trivy (HTML report)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.SERVICE_NAME }}-${{ inputs.CHART_NAME }}-${{ inputs.CHART_VER }}-html
        path: ${{ inputs.SERVICE_NAME }}-${{ inputs.CHART_NAME }}-${{ inputs.CHART_VER }}.html
        retention-days: 1