
runs:
  using: 'composite'
  steps:
    
    #Checkout code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    #Scan repo
    - name: Run gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITLEAKS_ENABLE_COMMENTS: false
        GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
      
    