inputs:
  defectdojo-url:
    required: true
    description: 'DefectDojo URL'
  defectdojo-username:
    required: true
    description: 'DefectDojo Username'
  defectdojo-password:
    required: true
    description: 'DefectDojo pwd'
  defectdojo-token:
    required: true
    description: 'DefectDojo API Key'
  cf-access-client-id:
    required: true
    description: 'CF access client id'
  cf-access-client-secret:
    required: true
    description: 'CF access client secret'

runs:
  using: 'composite'
  steps:
    
    #Checkout current commit
    - name: Checkout
      uses: actions/checkout@v4
    
    #Scan current commit with gitleaks, generate JSON report and catch exit code    
    - name: Run gitleaks
      #джоба не падает при старте по событию тега (актуально для продовых воркфлоу в продуктовых репах) и при пуше в main в tf-репах
      continue-on-error: true
      shell: bash
      id: gitleaks_scan
      run: |        
        docker run --rm \
          -v $(pwd):/path \
          -w /path \
          --user $(id -u):$(id -g) \
          ghcr.io/gitleaks/gitleaks:latest \
          git --log-opts "-1" \
          -f json \
          -r "gitleaks-${{ github.event.repository.name }}-${{ github.head_ref || github.ref_name }}.json" \
          || SECRET_EXIT_CODE=$?

        if [ -z $SECRET_EXIT_CODE ]
          then
            echo "Secrets has not been found"
          exit 0
        elif [ $SECRET_EXIT_CODE = "1" ]
        then
          echo "########Secrets or error encountered########"
          exit 1
        else
          echo "Error has been occured"
        fi
        
    #- name: Set up Python 3.12
    #  id: setup_python
    #  uses: actions/setup-python@v4
    #  with:
    #    python-version: 3.12
    #- name: Install dependencies
    #  id: install_dependencies
    #  shell: bash
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install setuptools dd-import
    #- name: Setup CF WARP
    #  uses: Boostport/setup-cloudflare-warp@v1
    #  with:
    #    organization: jjofinance
    #    auth_client_id: ${{ inputs.cf-access-client-id }}
    #    auth_client_secret: ${{ inputs.cf-access-client-secret }}

    - name: Upload Gitleaks Report to DefectDojo
      shell: bash
      env:
        DD_URL: ${{ inputs.defectdojo-url }}
        DD_API_KEY: ${{ inputs.defectdojo-token }}
        DD_PRODUCT_TYPE_NAME: JJO
        DD_PRODUCT_NAME: ${{ github.event.repository.name }}
        DD_ENGAGEMENT_NAME: ${{ github.head_ref || github.ref_name }}
        DD_TEST_NAME: Gitleaks
        DD_TEST_TYPE_NAME: Gitleaks Scan
        DD_FILE_NAME: ./results/gitleaks-${{ github.event.repository.name }}-${{ github.head_ref || github.ref_name }}.json
        DD_EXTRA_HEADER_1: CF-Access-Client-Id
        DD_EXTRA_HEADER_1_VALUE: ${{ inputs.cf-access-client-id }}
        DD_EXTRA_HEADER_2: CF-Access-Client-Secret
        DD_EXTRA_HEADER_2_VALUE: ${{ inputs.cf-access-client-secret }}
      run: |
        docker run --rm \
        -e DD_URL \
        -e DD_API_KEY \
        -e DD_PRODUCT_TYPE_NAME \
        -e DD_PRODUCT_NAME \
        -e DD_ENGAGEMENT_NAME \
        -e DD_TEST_NAME \
        -e DD_TEST_TYPE_NAME \
        -e DD_FILE_NAME \
        -e DD_EXTRA_HEADER_1 \
        -e DD_EXTRA_HEADER_1_VALUE \
        -e DD_EXTRA_HEADER_2 \
        -e DD_EXTRA_HEADER_2_VALUE \
        -v $(pwd):/usr/local/dd-import/results \
        maibornwolff/dd-import:latest dd-reimport-findings.sh

    - name: defectdojo_findings-threshold
      id: defectdojo-findings-threshold
      uses: portswigger-cloud/defectdojo-active-findings@main
      with:
        defectdojo-url: ${{ inputs.defectdojo-url }}
        defectdojo-username: ${{ inputs.defectdojo-username }}
        defectdojo-password: ${{ inputs.defectdojo-password }}
        defectdojo-product: ${{ github.event.repository.name }}
        total-threshold: 100
        critical-threshold: 10 
        high-threshold: 30
        medium-threshold: 50
        low-threshold: 100
        info-threshold: 1000

    - name: Upload gitleaks report to artifacts
      uses: actions/upload-artifact@v4
      #if: always()
      with:
        name: gitleaks-${{ github.event.repository.name }}-${{ github.head_ref || github.ref_name }}-json
        path: gitleaks-${{ github.event.repository.name }}-${{ github.head_ref || github.ref_name }}.json
        #retention-days: 1

    #- name: Download scan results artifact
    #  uses: actions/download-artifact@v4
    #  with:
    #    name: gitleaks-${{ github.event.repository.name }}-${{ github.head_ref || github.ref_name }}-json