# предлагаю в этом файле описать  логику выбора Trivy/Grype.
# В соответствии с тем, что используем, то и выбираем в качестве 
# actions. На вход условия подаем имя репозитория, а на вход action
# передаем список образов

inputs:
  GITHUB_REF:
    type: string
    required: true
  SERVICE_NAME:
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Trivy
      uses: aquasecurity/trivy-action@0.29.0
      with:
        image-ref: "ghcr.io/jjoinvest/${{ inputs.SERVICE_NAME }}:${{ inputs.GITHUB_REF }}"
        format: "template"
        template: "@$HOME/.local/bin/trivy-bin/contrib/html.tpl"
        output: "${{ SERVICE_NAME }}-${{ inputs.GITHUB_REF }}.html"
    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: ${{ SERVICE_NAME }}-${{ inputs.GITHUB_REF }}.htm.html