# предлагаю в этом файле описать  логику выбора Trivy/Grype.
# В соответствии с тем, что используем, то и выбираем в качестве 
# actions. На вход условия подаем имя репозитория, а на вход action
# передаем список образов

on:
  workflow_call:
    inputs:
      GITHUB_REF:
        type: string
        required: true
      SERVICE_NAME:
        type: string
        required: true

runs:
  using: 'composite'
  steps:
    - name: Debug input values
      run: echo "SERVICE_NAME=${{ inputs.SERVICE_NAME }}, GITHUB_REF=${{ inputs.GITHUB_REF }}"
      shell: bash
    - name: Run Trivy
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'ghcr.io/jjoinvest/${{ inputs.SERVICE_NAME }}:test-cs-load'
        format: 'template'
        template: "@./html.tpl"
        output: test.html
    - name: Check Trivy report
      run: |
        cat test.html
      shell: bash
    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: test.html
