# предлагаю в этом файле описать  логику выбора Trivy/Grype.
# В соответствии с тем, что используем, то и выбираем в качестве 
# actions. На вход условия подаем имя репозитория, а на вход action
# передаем список образов

on:
  workflow_call:
    inputs:
      GITHUB_REF:
        type: string
        required: true
      SERVICE_NAME:
        type: string
        required: true

runs:
  using: 'composite'
  steps:
    - name: Debug input values
      run: echo "SERVICE_NAME=${{ inputs.SERVICE_NAME }}, GITHUB_REF=${{ inputs.GITHUB_REF }}"
      shell: bash
    - name: Setup Trivy
      uses: aquasecurity/setup-trivy@v0.2.1
      with:
        version: "latest"
    - name: Check Trivy installation
      run: |
        echo "Checking Trivy installation..."
        ls -la $HOME/.local/bin/trivy-bin/trivy
        which trivy
      shell: bash
    - name: Check template file
      run: |
        echo "Checking template file..."
        ls -la $HOME/.local/bin/trivy-bin/contrib/html.tpl
      shell: bash
    - name: Run Trivy
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: 'ghcr.io/jjoinvest/${{ inputs.SERVICE_NAME }}:test-cs-load'
        format: 'template'
        template: "@/home/runner/.local/bin/trivy-bin/contrib/html.tpl"
        output: test.html