inputs:
  GITHUB_REF:
    type: string
    required: true
  SERVICE_NAME:
    type: string
    required: true

runs:
  using: 'composite'
  steps:
    - name: Extract tag name
      shell: bash
      run: |
        # Extract tag name

        echo "tag=${GITHUB_HEAD_REF:-${{ inputs.GITHUB_REF }}}" >> $GITHUB_OUTPUT
      id: extract_tag
    - uses: actions/checkout@v3
    - name: Run Hadolint (JSON report)
      uses: hadolint/hadolint-action@v3.1.0
      with:
        no-fail: true
        recursive: true
        format: json
        output-file: "${{ inputs.SERVICE_NAME }}-${{ steps.extract_tag.outputs.tag }}-hadolint.json"
    - name: Upload Hadolint (JSON report)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.SERVICE_NAME }}-${{ steps.extract_tag.outputs.tag }}-hadolint-json
        path: ${{ inputs.SERVICE_NAME }}-${{ steps.extract_tag.outputs.tag }}-hadolint.json
        retention-days: 1
    - name: Run Hadolint (Text report)
      uses: hadolint/hadolint-action@v3.1.0
      with:
        no-fail: true
        recursive: true
        format: tty
        output-file: "${{ inputs.SERVICE_NAME }}-${{ steps.extract_tag.outputs.tag }}-hadolint.txt"
    - name: Upload Hadolint (Text report)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.SERVICE_NAME }}-${{ steps.extract_tag.outputs.tag }}-hadolint-txt
        path: ${{ inputs.SERVICE_NAME }}-${{ steps.extract_tag.outputs.tag }}-hadolint.txt
        retention-days: 1 

    - name: test
      shell: bash
      run: |
        echo "hahaha"
        echo $INPUT_DOCKERFILE