inputs:
  FAIL_CONDITION:
    required: false
    type: string
    default: ''

runs:
  using: 'composite'
  steps:
    
    #Checkout code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    #Scan commit for leaked secrets (JSON)
    - name: Run trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: |
          ${{ inputs.FAIL_CONDITION }}
          --json
      id: scan_json
      continue-on-error: true

    #Scan commit for leaked secrets (text)
    - name: Run trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: |
          ${{ inputs.FAIL_CONDITION }}
          --no-update
      id: scan_txt
      continue-on-error: true

    #Save outputs to files
    - name: Save outputs to file
      shell: bash
      run: |
        echo '${{ steps.scan_json.outputs.result }}' > ${{ github.event.repository.name }}-${{ github.ref_name }}.json
        echo '${{ steps.scan_txt.outputs.result }}' > ${{ github.event.repository.name }}-${{ github.ref_name }}.txt
    
    #Upload trufflehog JSON report to workflow artifacts
    - name: Upload trufflehog (JSON report)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ github.ref_name }}-json
        path: ${{ github.event.repository.name }}-${{ github.ref_name }}.json
        #retention-days: 1

    #Upload trufflehog text report to workflow artifacts
    - name: Upload Grype (Text report)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ github.ref_name }}-txt
        path: ${{ github.event.repository.name }}-${{ github.ref_name }}.txt
        #retention-days: 1

