runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run Checkov 
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        quiet: false
        soft_fail: true
        framework: terraform
        output_format: cli,json
        output_file_path: console,reports/${{ github.event.repository.name }}-checkov.json
        download_external_modules: true
    - name: Upload Checkov (JSON report)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-checkov-json
        path: reports/${{ github.event.repository.name }}-checkov.json
        retention-days: 1